### ISSUE TITLE
Recent Query Filtering

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/api-archivist-nodejs#84]
"/archive/:archive/payload/recent" does not filter by archive.  Probably same thing for blocks

**Comment by JoelBCarter** [comment]
This was actually a client side issue caused by using array indexes with React.  The caused the client to not fully re-render when when new data was received making it _appear_ as if we returned data from multiple archives.  We had unit tests in place to ensure we didn't return data from other archives and as part of this investigation they were further improved (see Pull Request #88)
